export const gifUiEn = {
  "pdfToGif": {
    "privacyBanner": "All conversion runs in your browser. Files never leave your device.",
    "uploadTitle": "Upload Files",
    "uploadAriaLabel": "Upload PDF",
    "dropHint": "Drop {displayName} files here or click to upload",
    "pdfHint": "One PDF — each page becomes a frame (max {max})",
    "replacePdf": "Replace PDF",
    "loadingPages": " · Loading pages… {percent}%",
    "pageCount": " · {n} page(s)",
    "pageLabel": "Page {n}",
    "frameDelay": "Frame delay (ms)",
    "gifQuality": "GIF quality",
    "outputWidth": "Output width",
    "outputHeight": "Output height",
    "letterboxBg": "Letterbox background",
    "loopForever": "Loop forever",
    "createButton": "Create animated GIF",
    "encoding": "Encoding… {percent}%",
    "downloadGif": "Download GIF",
    "reset": "Reset",
    "encodingPages": "Encoding pages…",
    "preview": "Preview",
    "previewAlt": "Animated GIF preview",
    "fileSize": "File size: {size}",
    "loadingConverter": "Loading converter...",
    "messages": {
      "pdfLibraryLoading": "PDF library is loading. Please wait.",
      "pageLimit": "Only the first {max} pages are used (PDF has {total} pages).",
      "loadedPages": "Loaded {n} page(s) from PDF.",
      "failedLoadPdf": "Failed to load PDF",
      "selectPdfOnly": "Please select a PDF file.",
      "firstPdfOnly": "Using the first PDF only. Replace it by choosing another file.",
      "resetComplete": "Reset complete.",
      "minPages": "This PDF needs at least {min} pages to make an animated GIF.",
      "gifCreated": "Animated GIF created. Download below.",
      "failedCreateGif": "Failed to create GIF",
      "createFirst": "Create a GIF first.",
      "downloadStarted": "Download started.",
      "canvasUnavailable": "Canvas not available"
    }
  }
};

export const gifUiKo = {
  "pdfToGif": {
    "privacyBanner": "모든 변환은 브라우저에서 실행됩니다. 파일이 기기를 떠나지 않습니다.",
    "uploadTitle": "파일 업로드",
    "uploadAriaLabel": "PDF 업로드",
    "dropHint": "{displayName} 파일을 여기에 놓거나 클릭하여 업로드",
    "pdfHint": "PDF 하나 — 각 페이지가 프레임이 됩니다(최대 {max})",
    "replacePdf": "PDF 교체",
    "loadingPages": " · 페이지 로딩 중… {percent}%",
    "pageCount": " · {n}페이지",
    "pageLabel": "페이지 {n}",
    "frameDelay": "프레임 지연 (ms)",
    "gifQuality": "GIF 품질",
    "outputWidth": "출력 너비",
    "outputHeight": "출력 높이",
    "letterboxBg": "레터박스 배경",
    "loopForever": "무한 반복",
    "createButton": "애니메이션 GIF 만들기",
    "encoding": "인코딩 중… {percent}%",
    "downloadGif": "GIF 다운로드",
    "reset": "초기화",
    "encodingPages": "페이지 인코딩 중…",
    "preview": "미리보기",
    "previewAlt": "애니메이션 GIF 미리보기",
    "fileSize": "파일 크기: {size}",
    "loadingConverter": "변환기 로딩 중...",
    "messages": {
      "pdfLibraryLoading": "PDF 라이브러리 로딩 중입니다. 잠시 기다려 주세요.",
      "pageLimit": "처음 {max}페이지만 사용됩니다(PDF 총 {total}페이지).",
      "loadedPages": "PDF에서 {n}페이지를 불러왔습니다.",
      "failedLoadPdf": "PDF를 불러오지 못했습니다",
      "selectPdfOnly": "PDF 파일을 선택해 주세요.",
      "firstPdfOnly": "첫 번째 PDF만 사용합니다. 다른 파일을 선택해 교체할 수 있습니다.",
      "resetComplete": "초기화 완료.",
      "minPages": "애니메이션 GIF를 만들려면 PDF에 최소 {min}페이지가 필요합니다.",
      "gifCreated": "애니메이션 GIF가 만들어졌습니다. 아래에서 다운로드하세요.",
      "failedCreateGif": "GIF를 만들지 못했습니다",
      "createFirst": "먼저 GIF를 만드세요.",
      "downloadStarted": "다운로드가 시작되었습니다.",
      "canvasUnavailable": "캔버스를 사용할 수 없습니다"
    }
  }
};
