export const pdfUiEn = {
  "mergePdf": {
    "privacyBanner": "All processing runs in your browser. Files never leave your device.",
    "uploadTitle": "Upload Files",
    "dropHint": "Drop PDF files here or click to upload",
    "supportsMultiple": "Supports multiple files",
    "uploadedFiles": "Uploaded files ({n})",
    "previewOf": "Preview of {name}",
    "moveUp": "Move up",
    "moveDown": "Move down",
    "remove": "Remove",
    "mergeButton": "Merge PDFs",
    "merging": "Merging...",
    "reset": "Reset",
    "add": "Add",
    "mergingProgress": "Merging... {current} of {total}",
    "filesSelected": "{n} file(s) selected · {size} MB total",
    "mergeSuccessTitle": "PDFs merged successfully",
    "downloadPdf": "Download PDF",
    "loadingTool": "Loading tool...",
    "messages": {
      "addOnePdf": "Please add at least one PDF file.",
      "needTwoPdfs": "Please add at least two PDF files to merge.",
      "mergeSuccess": "PDFs merged successfully.",
      "mergeFailed": "Failed to merge PDFs."
    }
  },
  "imageToPdf": {
    "privacyBanner": "All conversion runs in your browser. Files never leave your device.",
    "uploadTitle": "Upload Files",
    "dropImages": "Drop images here or click to upload",
    "dropFormat": "Drop {format} images here or click to upload",
    "mixedFormatsHint": "JPG, PNG, HEIC, WEBP, TIFF, and more—mixed formats in one batch",
    "supportsMultiple": "Supports multiple files",
    "uploadedFiles": "Uploaded files ({n})",
    "previewWarning": "Preview warning: {text}",
    "failedPreviewList": "Failed ({n}): {names}",
    "generatingPreviews": "Generating previews…",
    "couldNotDecode": "Could not decode preview",
    "stillConvertHint": "You can still convert to PDF. If conversion fails, remove this file.",
    "remove": "Remove",
    "options": "Options",
    "pageSize": "Page size",
    "fitToImage": "Fit to image",
    "a4": "A4",
    "fitHint": "Each page matches its image size (no margins)",
    "a4Hint": "Fixed A4 size, image scaled to fit (may have margins)",
    "pageOrientation": "Page orientation",
    "portrait": "Portrait",
    "landscape": "Landscape",
    "convertButton": "Convert to PDF",
    "converting": "Converting...",
    "reset": "Reset",
    "add": "Add",
    "convertingProgress": "Converting... {current} of {total}",
    "filesSelected": "{n} file(s) selected",
    "pdfCreatedTitle": "PDF created successfully",
    "downloadPdf": "Download PDF",
    "loadingConverter": "Loading converter...",
    "messages": {
      "addSupportedImage": "Please add at least one supported image file.",
      "selectFormatImages": "Please select {format} images.",
      "addImagesFirst": "Please add images first.",
      "pdfCreated": "PDF created successfully.",
      "convertFailed": "Failed to convert to PDF.",
      "somePreviewsFailed": "Some previews could not be generated. Check the file list below."
    }
  }
};

export const pdfUiKo = {
  "mergePdf": {
    "privacyBanner": "모든 처리는 브라우저에서 실행됩니다. 파일이 기기를 떠나지 않습니다.",
    "uploadTitle": "파일 업로드",
    "dropHint": "PDF 파일을 여기에 놓거나 클릭하여 업로드",
    "supportsMultiple": "여러 파일 지원",
    "uploadedFiles": "업로드된 파일 ({n})",
    "previewOf": "{name} 미리보기",
    "moveUp": "위로",
    "moveDown": "아래로",
    "remove": "제거",
    "mergeButton": "PDF 병합",
    "merging": "병합 중...",
    "reset": "초기화",
    "add": "추가",
    "mergingProgress": "병합 중... {current} / {total}",
    "filesSelected": "{n}개 파일 선택 · 총 {size} MB",
    "mergeSuccessTitle": "PDF 병합 완료",
    "downloadPdf": "PDF 다운로드",
    "loadingTool": "도구 로딩 중...",
    "messages": {
      "addOnePdf": "PDF 파일을 1개 이상 추가해 주세요.",
      "needTwoPdfs": "병합하려면 PDF 파일을 2개 이상 추가해 주세요.",
      "mergeSuccess": "PDF 병합이 완료되었습니다.",
      "mergeFailed": "PDF 병합에 실패했습니다."
    }
  },
  "imageToPdf": {
    "privacyBanner": "모든 변환은 브라우저에서 실행됩니다. 파일이 기기를 떠나지 않습니다.",
    "uploadTitle": "파일 업로드",
    "dropImages": "이미지를 여기에 놓거나 클릭하여 업로드",
    "dropFormat": "{format} 이미지를 여기에 놓거나 클릭하여 업로드",
    "mixedFormatsHint": "JPG, PNG, HEIC, WEBP, TIFF 등 — 한 번에 혼합 형식 가능",
    "supportsMultiple": "여러 파일 지원",
    "uploadedFiles": "업로드된 파일 ({n})",
    "previewWarning": "미리보기 경고: {text}",
    "failedPreviewList": "실패 ({n}): {names}",
    "generatingPreviews": "미리보기 생성 중…",
    "couldNotDecode": "미리보기를 디코딩할 수 없습니다",
    "stillConvertHint": "PDF 변환은 시도할 수 있습니다. 변환에 실패하면 이 파일을 제거하세요.",
    "remove": "제거",
    "options": "옵션",
    "pageSize": "페이지 크기",
    "fitToImage": "이미지 맞춤",
    "a4": "A4",
    "fitHint": "각 페이지가 이미지 크기에 맞습니다(여백 없음)",
    "a4Hint": "고정 A4 크기, 이미지가 맞게 축소됩니다(여백 있을 수 있음)",
    "pageOrientation": "페이지 방향",
    "portrait": "세로",
    "landscape": "가로",
    "convertButton": "PDF로 변환",
    "converting": "변환 중...",
    "reset": "초기화",
    "add": "추가",
    "convertingProgress": "변환 중... {current} / {total}",
    "filesSelected": "{n}개 파일 선택",
    "pdfCreatedTitle": "PDF 생성 완료",
    "downloadPdf": "PDF 다운로드",
    "loadingConverter": "변환기 로딩 중...",
    "messages": {
      "addSupportedImage": "지원되는 이미지 파일을 1개 이상 추가해 주세요.",
      "selectFormatImages": "{format} 이미지를 선택해 주세요.",
      "addImagesFirst": "먼저 이미지를 추가해 주세요.",
      "pdfCreated": "PDF가 생성되었습니다.",
      "convertFailed": "PDF 변환에 실패했습니다.",
      "somePreviewsFailed": "일부 미리보기를 생성할 수 없습니다. 아래 파일 목록을 확인하세요."
    }
  }
};
