export const randomUiEn = {
  "passwordGenerator": {
    "privacyBanner": "All password generation runs in your browser. Data is never sent to any server.",
    "generatedPassword": "Generated Password",
    "placeholder": "Click Generate to create password",
    "copy": "Copy",
    "passwordLength": "Password Length: {length}",
    "uppercase": "Uppercase",
    "lowercase": "Lowercase",
    "numbers": "Numbers",
    "symbols": "Symbols",
    "passwordStrength": "Password Strength",
    "strengthWeak": "Weak",
    "strengthMedium": "Medium",
    "strengthStrong": "Strong",
    "generateButton": "Generate Password",
    "messages": {
      "needOneOption": "At least one option must be selected",
      "noPasswordToCopy": "No password to copy",
      "copied": "Password copied to clipboard!",
      "copyFailed": "Failed to copy password"
    }
  },
  "randomNumberGenerator": {
    "privacyBanner": "All number generation runs in your browser. Data is never sent to any server.",
    "settings": "Settings",
    "minimumValue": "Minimum Value",
    "maximumValue": "Maximum Value",
    "quantity": "Quantity",
    "separator": "Separator",
    "separatorSpace": "Space",
    "separatorComma": "Comma",
    "separatorNewline": "New Line",
    "allowDuplicates": "Allow Duplicates",
    "sortNumbers": "Sort Numbers",
    "generating": "Generating...",
    "generateButton": "Generate Numbers",
    "generatedNumbers": "Generated Numbers",
    "copy": "Copy",
    "download": "Download",
    "clear": "Clear",
    "count": "Count:",
    "min": "Min:",
    "max": "Max:",
    "average": "Average:",
    "emptyResult": "Generated numbers will appear here...",
    "messages": {
      "enterMin": "Please enter a minimum value",
      "enterMax": "Please enter a maximum value",
      "maxAdjusted": "Maximum value adjusted to match minimum value",
      "enterQuantity": "Please enter a quantity",
      "quantityMin": "Quantity must be at least 1",
      "quantityMax": "Maximum quantity is 1000",
      "uniqueLimit": "Maximum unique numbers possible in this range: {range}",
      "cannotGenerateUnique": "Cannot generate {qty} unique numbers in this range",
      "generatedSuccess": "Generated {n} random number(s) successfully",
      "generateFailed": "Failed to generate numbers",
      "noNumbersToCopy": "No numbers to copy",
      "copied": "Numbers copied to clipboard",
      "copyFailed": "Failed to copy numbers to clipboard",
      "noNumbersToDownload": "No numbers to download",
      "downloaded": "Numbers downloaded successfully"
    }
  }
};

export const randomUiKo = {
  "passwordGenerator": {
    "privacyBanner": "모든 비밀번호 생성은 브라우저에서 실행됩니다. 데이터는 서버로 전송되지 않습니다.",
    "generatedPassword": "생성된 비밀번호",
    "placeholder": "생성을 클릭해 비밀번호를 만드세요",
    "copy": "복사",
    "passwordLength": "비밀번호 길이: {length}",
    "uppercase": "대문자",
    "lowercase": "소문자",
    "numbers": "숫자",
    "symbols": "기호",
    "passwordStrength": "비밀번호 강도",
    "strengthWeak": "약함",
    "strengthMedium": "보통",
    "strengthStrong": "강함",
    "generateButton": "비밀번호 생성",
    "messages": {
      "needOneOption": "최소 한 가지 옵션을 선택해야 합니다",
      "noPasswordToCopy": "복사할 비밀번호가 없습니다",
      "copied": "비밀번호가 클립보드에 복사되었습니다!",
      "copyFailed": "비밀번호 복사에 실패했습니다"
    }
  },
  "randomNumberGenerator": {
    "privacyBanner": "모든 숫자 생성은 브라우저에서 실행됩니다. 데이터는 서버로 전송되지 않습니다.",
    "settings": "설정",
    "minimumValue": "최솟값",
    "maximumValue": "최댓값",
    "quantity": "개수",
    "separator": "구분자",
    "separatorSpace": "공백",
    "separatorComma": "쉼표",
    "separatorNewline": "줄바꿈",
    "allowDuplicates": "중복 허용",
    "sortNumbers": "숫자 정렬",
    "generating": "생성 중...",
    "generateButton": "숫자 생성",
    "generatedNumbers": "생성된 숫자",
    "copy": "복사",
    "download": "다운로드",
    "clear": "지우기",
    "count": "개수:",
    "min": "최소:",
    "max": "최대:",
    "average": "평균:",
    "emptyResult": "생성된 숫자가 여기에 표시됩니다...",
    "messages": {
      "enterMin": "최솟값을 입력해 주세요",
      "enterMax": "최댓값을 입력해 주세요",
      "maxAdjusted": "최댓값이 최솟값에 맞게 조정되었습니다",
      "enterQuantity": "개수를 입력해 주세요",
      "quantityMin": "개수는 최소 1이어야 합니다",
      "quantityMax": "최대 개수는 1000입니다",
      "uniqueLimit": "이 범위에서 가능한 최대 고유 숫자: {range}",
      "cannotGenerateUnique": "이 범위에서 고유 숫자 {qty}개를 생성할 수 없습니다",
      "generatedSuccess": "난수 {n}개를 성공적으로 생성했습니다",
      "generateFailed": "숫자 생성에 실패했습니다",
      "noNumbersToCopy": "복사할 숫자가 없습니다",
      "copied": "숫자가 클립보드에 복사되었습니다",
      "copyFailed": "숫자 클립보드 복사에 실패했습니다",
      "noNumbersToDownload": "다운로드할 숫자가 없습니다",
      "downloaded": "숫자가 성공적으로 다운로드되었습니다"
    }
  }
};
