export const seoUiEn = {
  "faviconGenerator": {
    "privacyBanner": "All favicon generation runs in your browser. Files never leave your device.",
    "uploadImage": "Upload Image",
    "dropImageHere": "Drop image here or click to upload",
    "recommendedSize": "Recommended: Square image, minimum 260×260 pixels",
    "changeImage": "Change Image",
    "reset": "Reset",
    "options": "Options",
    "platforms": "Platforms",
    "platformBasic": "Basic favicon (favicon.ico)",
    "platformApple": "Apple Touch Icons",
    "platformAndroid": "Android/Chrome Icons",
    "platformWindows": "Windows Tiles",
    "platformSafari": "Safari Pinned Tab",
    "backgroundLabel": "Background (for transparent source images)",
    "noBackground": "No background (keep transparency)",
    "transparentHintOn": "Icons are drawn on a transparent canvas. Opaque pixels in your image are unchanged.",
    "transparentHintOff": "Transparent areas in your image are filled with the color below.",
    "fillColor": "Fill color",
    "themeColor": "Theme & manifest color (meta tags only)",
    "siteName": "Site Name",
    "siteNamePlaceholder": "e.g., WithusTools",
    "shortName": "Short Name",
    "shortNamePlaceholder": "e.g., Withus",
    "faviconOutputPath": "Favicon output path",
    "faviconOutputPathPlaceholder": "e.g., /assets/icons/",
    "generateButton": "Generate Favicons",
    "generatedFavicons": "Generated Favicons",
    "previewDisclaimer": "These previews are for illustrative purposes only.",
    "htmlCode": "HTML Code",
    "siteWebmanifest": "site.webmanifest",
    "browserconfigXml": "browserconfig.xml",
    "copy": "Copy",
    "copied": "Copied!",
    "downloadPackage": "Download Favicon Package",
    "previewAlt": "Preview",
    "messages": {
      "selectImageFile": "Please select an image file (PNG, JPG, GIF, etc.).",
      "failedReadFile": "Failed to read file.",
      "failedLoadImage": "Failed to load image. The file may be corrupted.",
      "imageTooSmall": "Image is too small. Minimum size is 260x260 pixels.",
      "failedGenerate": "Failed to generate favicons",
      "packageDownloaded": "Package downloaded successfully!",
      "failedDownload": "Failed to download package",
      "pleaseDropImage": "Please drop an image file.",
      "pleaseDropImageType": "Please drop an image file (PNG, JPG, GIF, etc.)."
    }
  },
  "metaTagGenerator": {
    "input": "Input",
    "tabBasic": "Basic Meta Tags",
    "tabOpenGraph": "Open Graph",
    "tabTwitter": "Twitter Cards",
    "syncFromBasic": "Use Basic title/description for OG & Twitter when empty",
    "titleTag": "Title Tag",
    "titlePlaceholder": "Enter page title",
    "metaDescription": "Meta Description",
    "descriptionPlaceholder": "Enter page description",
    "metaKeywords": "Meta Keywords",
    "keywordsPlaceholder": "keyword1, keyword2, keyword3",
    "robots": "Robots",
    "robotsIndexFollow": "Index, Follow",
    "robotsNoindexFollow": "No Index, Follow",
    "robotsIndexNofollow": "Index, No Follow",
    "robotsNoindexNofollow": "No Index, No Follow",
    "canonicalUrl": "Canonical URL",
    "canonicalPlaceholder": "https://example.com/page",
    "ogType": "OG Type",
    "ogTypeWebsite": "Website",
    "ogTypeArticle": "Article",
    "ogTypeProduct": "Product",
    "ogTypeProfile": "Profile",
    "ogSiteName": "OG Site Name",
    "ogSiteNamePlaceholder": "Site or brand name",
    "ogTitle": "OG Title",
    "ogTitlePlaceholder": "Enter Open Graph title",
    "ogDescription": "OG Description",
    "ogDescriptionPlaceholder": "Enter Open Graph description",
    "ogUrl": "OG URL",
    "ogUrlPlaceholder": "https://example.com",
    "ogImageUrl": "OG Image URL",
    "ogImagePlaceholder": "https://example.com/image.jpg",
    "ogImageWidth": "OG Image Width",
    "ogImageHeight": "OG Image Height",
    "ogImageAlt": "OG Image Alt",
    "ogImageAltPlaceholder": "Image description for accessibility",
    "twitterCardType": "Twitter Card Type",
    "twitterCardSummary": "Summary",
    "twitterCardSummaryLarge": "Summary Large Image",
    "twitterCardApp": "App",
    "twitterCardPlayer": "Player",
    "twitterTitle": "Twitter Title",
    "twitterTitlePlaceholder": "Enter Twitter title",
    "twitterDescription": "Twitter Description",
    "twitterDescriptionPlaceholder": "Enter Twitter description",
    "twitterImageUrl": "Twitter Image URL",
    "generatedMetaTags": "Generated Meta Tags",
    "saveHtml": "Save HTML",
    "copyHtml": "Copy HTML",
    "emptyOutput": "Generated meta tags will appear here...",
    "preview": "Preview",
    "searchResult": "Search Result",
    "previewTitle": "Page title will appear here",
    "previewDescription": "Page description will appear here.",
    "socialCard": "Social Card",
    "noImage": "No image",
    "messages": {
      "copied": "Meta tags copied to clipboard!",
      "copyFailed": "Failed to copy. Try again or copy manually.",
      "noSave": "No meta tags to save.",
      "saved": "Meta tags saved as meta-tags.html"
    }
  },
  "robotsGenerator": {
    "sitemapUrl": "Sitemap URL",
    "sitemapPlaceholder": "https://example.com/sitemap.xml",
    "userAgentRules": "User Agent Rules",
    "userAgentPlaceholder": "User-agent (e.g., *, Googlebot)",
    "pathPlaceholder": "Path (e.g., /, /private/)",
    "ruleAllow": "Allow",
    "ruleDisallow": "Disallow",
    "remove": "Remove",
    "addRule": "+ Add Rule",
    "crawlDelay": "Crawl Delay (Optional)",
    "crawlDelayPlaceholder": "Enter delay in seconds",
    "crawlDelayNote": "Note: Crawl-delay is ignored by Google. Supported by Yandex and some other crawlers.",
    "generatedRobots": "Generated Robots.txt",
    "copy": "Copy",
    "download": "Download",
    "emptyOutput": "Generated robots.txt will appear here...",
    "moveUp": "Move up",
    "moveDown": "Move down",
    "messages": {
      "noCopy": "No content to copy. Add at least one rule with User-agent and Path.",
      "copied": "Robots.txt copied to clipboard!",
      "copyFailed": "Failed to copy. Try again or copy manually.",
      "noDownload": "No content to download. Add at least one rule with User-agent and Path."
    }
  },
  "sitemapGenerator": {
    "websiteUrl": "Website URL",
    "websitePlaceholder": "https://example.com",
    "lastModified": "Last modified",
    "emptyUrlHint": "(empty defaults to today)",
    "urlList": "URL List",
    "addUrl": "+ Add URL",
    "urlPlaceholder": "https://example.com/page",
    "frequency": "Frequency",
    "freqAlways": "Always",
    "freqHourly": "Hourly",
    "freqDaily": "Daily",
    "freqWeekly": "Weekly",
    "freqMonthly": "Monthly",
    "freqYearly": "Yearly",
    "freqNever": "Never",
    "priority": "Priority",
    "remove": "Remove",
    "generatedSitemap": "Generated Sitemap",
    "copyXml": "Copy XML",
    "download": "Download",
    "moveUp": "Move up",
    "moveDown": "Move down",
    "messages": {
      "enterWebsiteUrl": "Enter Website URL first.",
      "copied": "XML copied to clipboard!",
      "copyFailed": "Failed to copy. Try again or copy manually.",
      "missingWebsiteUrl": "Please enter website URL"
    }
  }
};

export const seoUiKo = {
  "faviconGenerator": {
    "privacyBanner": "모든 파비콘 생성은 브라우저에서 실행됩니다. 파일은 기기를 떠나지 않습니다.",
    "uploadImage": "이미지 업로드",
    "dropImageHere": "이미지를 여기에 놓거나 클릭하여 업로드",
    "recommendedSize": "권장: 정사각형 이미지, 최소 260×260 픽셀",
    "changeImage": "이미지 변경",
    "reset": "초기화",
    "options": "옵션",
    "platforms": "플랫폼",
    "platformBasic": "기본 파비콘 (favicon.ico)",
    "platformApple": "Apple 터치 아이콘",
    "platformAndroid": "Android/Chrome 아이콘",
    "platformWindows": "Windows 타일",
    "platformSafari": "Safari 고정 탭",
    "backgroundLabel": "배경 (투명 원본 이미지용)",
    "noBackground": "배경 없음 (투명도 유지)",
    "transparentHintOn": "아이콘은 투명 캔버스에 그려집니다. 이미지의 불투명 픽셀은 변경되지 않습니다.",
    "transparentHintOff": "이미지의 투명 영역은 아래 색으로 채워집니다.",
    "fillColor": "채우기 색",
    "themeColor": "테마·매니페스트 색 (메타 태그만)",
    "siteName": "사이트 이름",
    "siteNamePlaceholder": "예: WithusTools",
    "shortName": "짧은 이름",
    "shortNamePlaceholder": "예: Withus",
    "faviconOutputPath": "파비콘 출력 경로",
    "faviconOutputPathPlaceholder": "예: /assets/icons/",
    "generateButton": "파비콘 생성",
    "generatedFavicons": "생성된 파비콘",
    "previewDisclaimer": "미리보기는 참고용입니다.",
    "htmlCode": "HTML 코드",
    "siteWebmanifest": "site.webmanifest",
    "browserconfigXml": "browserconfig.xml",
    "copy": "복사",
    "copied": "복사됨!",
    "downloadPackage": "파비콘 패키지 다운로드",
    "previewAlt": "미리보기",
    "messages": {
      "selectImageFile": "이미지 파일(PNG, JPG, GIF 등)을 선택해 주세요.",
      "failedReadFile": "파일을 읽지 못했습니다.",
      "failedLoadImage": "이미지를 불러오지 못했습니다. 파일이 손상되었을 수 있습니다.",
      "imageTooSmall": "이미지가 너무 작습니다. 최소 크기는 260×260 픽셀입니다.",
      "failedGenerate": "파비콘 생성에 실패했습니다",
      "packageDownloaded": "패키지가 성공적으로 다운로드되었습니다!",
      "failedDownload": "패키지 다운로드에 실패했습니다",
      "pleaseDropImage": "이미지 파일을 놓아 주세요.",
      "pleaseDropImageType": "이미지 파일(PNG, JPG, GIF 등)을 놓아 주세요."
    }
  },
  "metaTagGenerator": {
    "input": "입력",
    "tabBasic": "기본 메타 태그",
    "tabOpenGraph": "Open Graph",
    "tabTwitter": "Twitter Cards",
    "syncFromBasic": "비어 있을 때 OG·Twitter에 기본 제목/설명 사용",
    "titleTag": "제목 태그",
    "titlePlaceholder": "페이지 제목 입력",
    "metaDescription": "메타 설명",
    "descriptionPlaceholder": "페이지 설명 입력",
    "metaKeywords": "메타 키워드",
    "keywordsPlaceholder": "keyword1, keyword2, keyword3",
    "robots": "Robots",
    "robotsIndexFollow": "Index, Follow",
    "robotsNoindexFollow": "No Index, Follow",
    "robotsIndexNofollow": "Index, No Follow",
    "robotsNoindexNofollow": "No Index, No Follow",
    "canonicalUrl": "Canonical URL",
    "canonicalPlaceholder": "https://example.com/page",
    "ogType": "OG 유형",
    "ogTypeWebsite": "Website",
    "ogTypeArticle": "Article",
    "ogTypeProduct": "Product",
    "ogTypeProfile": "Profile",
    "ogSiteName": "OG 사이트 이름",
    "ogSiteNamePlaceholder": "사이트 또는 브랜드 이름",
    "ogTitle": "OG 제목",
    "ogTitlePlaceholder": "Open Graph 제목 입력",
    "ogDescription": "OG 설명",
    "ogDescriptionPlaceholder": "Open Graph 설명 입력",
    "ogUrl": "OG URL",
    "ogUrlPlaceholder": "https://example.com",
    "ogImageUrl": "OG 이미지 URL",
    "ogImagePlaceholder": "https://example.com/image.jpg",
    "ogImageWidth": "OG 이미지 너비",
    "ogImageHeight": "OG 이미지 높이",
    "ogImageAlt": "OG 이미지 Alt",
    "ogImageAltPlaceholder": "접근성용 이미지 설명",
    "twitterCardType": "Twitter Card 유형",
    "twitterCardSummary": "Summary",
    "twitterCardSummaryLarge": "Summary Large Image",
    "twitterCardApp": "App",
    "twitterCardPlayer": "Player",
    "twitterTitle": "Twitter 제목",
    "twitterTitlePlaceholder": "Twitter 제목 입력",
    "twitterDescription": "Twitter 설명",
    "twitterDescriptionPlaceholder": "Twitter 설명 입력",
    "twitterImageUrl": "Twitter 이미지 URL",
    "generatedMetaTags": "생성된 메타 태그",
    "saveHtml": "HTML 저장",
    "copyHtml": "HTML 복사",
    "emptyOutput": "생성된 메타 태그가 여기에 표시됩니다...",
    "preview": "미리보기",
    "searchResult": "검색 결과",
    "previewTitle": "페이지 제목이 여기에 표시됩니다",
    "previewDescription": "페이지 설명이 여기에 표시됩니다.",
    "socialCard": "소셜 카드",
    "noImage": "이미지 없음",
    "messages": {
      "copied": "메타 태그가 클립보드에 복사되었습니다!",
      "copyFailed": "복사에 실패했습니다. 다시 시도하거나 수동으로 복사하세요.",
      "noSave": "저장할 메타 태그가 없습니다.",
      "saved": "메타 태그가 meta-tags.html로 저장되었습니다"
    }
  },
  "robotsGenerator": {
    "sitemapUrl": "사이트맵 URL",
    "sitemapPlaceholder": "https://example.com/sitemap.xml",
    "userAgentRules": "User Agent 규칙",
    "userAgentPlaceholder": "User-agent (예: *, Googlebot)",
    "pathPlaceholder": "경로 (예: /, /private/)",
    "ruleAllow": "Allow",
    "ruleDisallow": "Disallow",
    "remove": "제거",
    "addRule": "+ 규칙 추가",
    "crawlDelay": "Crawl Delay (선택)",
    "crawlDelayPlaceholder": "지연 시간(초) 입력",
    "crawlDelayNote": "참고: Crawl-delay는 Google에서 무시됩니다. Yandex 등 일부 크롤러에서 지원합니다.",
    "generatedRobots": "생성된 Robots.txt",
    "copy": "복사",
    "download": "다운로드",
    "emptyOutput": "생성된 robots.txt가 여기에 표시됩니다...",
    "moveUp": "위로 이동",
    "moveDown": "아래로 이동",
    "messages": {
      "noCopy": "복사할 내용이 없습니다. User-agent와 경로가 있는 규칙을 최소 하나 추가하세요.",
      "copied": "Robots.txt가 클립보드에 복사되었습니다!",
      "copyFailed": "복사에 실패했습니다. 다시 시도하거나 수동으로 복사하세요.",
      "noDownload": "다운로드할 내용이 없습니다. User-agent와 경로가 있는 규칙을 최소 하나 추가하세요."
    }
  },
  "sitemapGenerator": {
    "websiteUrl": "웹사이트 URL",
    "websitePlaceholder": "https://example.com",
    "lastModified": "최종 수정",
    "emptyUrlHint": "(비어 있으면 오늘)",
    "urlList": "URL 목록",
    "addUrl": "+ URL 추가",
    "urlPlaceholder": "https://example.com/page",
    "frequency": "변경 빈도",
    "freqAlways": "Always",
    "freqHourly": "Hourly",
    "freqDaily": "Daily",
    "freqWeekly": "Weekly",
    "freqMonthly": "Monthly",
    "freqYearly": "Yearly",
    "freqNever": "Never",
    "priority": "우선순위",
    "remove": "제거",
    "generatedSitemap": "생성된 사이트맵",
    "copyXml": "XML 복사",
    "download": "다운로드",
    "moveUp": "위로 이동",
    "moveDown": "아래로 이동",
    "messages": {
      "enterWebsiteUrl": "먼저 웹사이트 URL을 입력하세요.",
      "copied": "XML이 클립보드에 복사되었습니다!",
      "copyFailed": "복사에 실패했습니다. 다시 시도하거나 수동으로 복사하세요.",
      "missingWebsiteUrl": "웹사이트 URL을 입력해 주세요"
    }
  }
};
